import { useState, useEffect, useCallback } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "@/hooks/use-toast";

interface OrderItem {
  id: string;
  product_name: string;
  product_image: string | null;
  quantity: number;
  price: number;
  total: number;
}

interface Order {
  id: string;
  order_number: string;
  status: "pending" | "confirmed" | "packed" | "shipped" | "delivered" | "cancelled";
  subtotal: number;
  shipping_cost: number;
  total: number;
  shipping_address: {
    full_name: string;
    phone: string;
    address_line1: string;
    address_line2?: string;
    city: string;
    state: string;
    pincode: string;
  };
  notes: string | null;
  cancelled_reason: string | null;
  placed_at: string;
  confirmed_at: string | null;
  packed_at: string | null;
  shipped_at: string | null;
  delivered_at: string | null;
  cancelled_at: string | null;
  items: OrderItem[];
}

export function useOrders() {
  const { user } = useAuth();
  const [orders, setOrders] = useState<Order[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const fetchOrders = useCallback(async () => {
    if (!user) {
      setOrders([]);
      return;
    }

    setIsLoading(true);
    try {
      const { data, error } = await supabase
        .from("orders")
        .select(`
          *,
          items:order_items (*)
        `)
        .eq("user_id", user.id)
        .order("placed_at", { ascending: false });

      if (error) throw error;
      setOrders((data as unknown as Order[]) || []);
    } catch (error) {
      console.error("Error fetching orders:", error);
    } finally {
      setIsLoading(false);
    }
  }, [user]);

  useEffect(() => {
    fetchOrders();
  }, [fetchOrders]);

  return { orders, isLoading, refetch: fetchOrders };
}

export function useOrder(orderId: string) {
  const { user } = useAuth();
  const [order, setOrder] = useState<Order | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchOrder = async () => {
      if (!user || !orderId) {
        setOrder(null);
        setIsLoading(false);
        return;
      }

      try {
        const { data, error } = await supabase
          .from("orders")
          .select(`
            *,
            items:order_items (*)
          `)
          .eq("id", orderId)
          .eq("user_id", user.id)
          .single();

        if (error) throw error;
        setOrder(data as unknown as Order);
      } catch (error) {
        console.error("Error fetching order:", error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchOrder();
  }, [user, orderId]);

  return { order, isLoading };
}

interface CreateOrderParams {
  shippingAddress: {
    full_name: string;
    phone: string;
    address_line1: string;
    address_line2?: string;
    city: string;
    state: string;
    pincode: string;
  };
  items: {
    product_id: string;
    product_name: string;
    product_image?: string;
    quantity: number;
    price: number;
  }[];
  subtotal: number;
  shippingCost: number;
  notes?: string;
}

export function useCreateOrder() {
  const { user } = useAuth();
  const [isLoading, setIsLoading] = useState(false);

  const createOrder = async (params: CreateOrderParams) => {
    if (!user) {
      toast({
        title: "Please login",
        description: "You need to login to place an order",
        variant: "destructive",
      });
      return { order: null, error: new Error("Not authenticated") };
    }

    setIsLoading(true);
    try {
      // Create order - order_number is auto-generated by trigger
      const { data: order, error: orderError } = await supabase
        .from("orders")
        .insert({
          user_id: user.id,
          shipping_address: params.shippingAddress,
          subtotal: params.subtotal,
          shipping_cost: params.shippingCost,
          total: params.subtotal + params.shippingCost,
          notes: params.notes || null,
          order_number: "", // Will be overwritten by trigger
        } as any)
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = params.items.map((item) => ({
        order_id: order.id,
        product_id: item.product_id,
        product_name: item.product_name,
        product_image: item.product_image,
        quantity: item.quantity,
        price: item.price,
        total: item.price * item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from("order_items")
        .insert(orderItems);

      if (itemsError) throw itemsError;

      // Update product stock by calling the RPC function
      for (const item of params.items) {
        await supabase.rpc("decrement_stock" as any, {
          p_product_id: item.product_id,
          p_quantity: item.quantity,
        });
      }

      toast({
        title: "Order placed!",
        description: `Your order ${order.order_number} has been placed successfully`,
      });

      return { order, error: null };
    } catch (error) {
      console.error("Error creating order:", error);
      toast({
        title: "Error",
        description: "Failed to place order. Please try again.",
        variant: "destructive",
      });
      return { order: null, error: error as Error };
    } finally {
      setIsLoading(false);
    }
  };

  return { createOrder, isLoading };
}
